theme: jekyll-theme-hacker

https://solaimanhakkani.github.io/Registration-Form-Responsive/
https://solaimanhakkani.github.io/form-demo/
https://solaimanhakkani.github.io/landingpage/
https://solaimanhakkani.github.io/hw-third/
